stages:
  - build

before_script:
  - apt-get update -y
  - apt-get -y install liblouis-dev

rust-stable:
  stage: build
  image: rust:stretch
  script:
    - cargo build --verbose
    - cargo test --verbose