stages:
  - build

before_script:
  - apt-get update -y
  - apt-get -y install clang make

rust-stable:
  stage: build
  image: rust:slim-stretch
  script:
    - cargo build
    - cargo test

variables:
  RUST_BACKTRACE: "1"
  RUST_LOG: "warn"