stages:
  - build

before_script:
  - apt-get update -y
  - apt-get -y install liblouis-dev clang

rust-stable:
  stage: build
  image: rust:stretch-slim
  script:
    - cargo build
    - cargo test

variables:
  RUST_BACKTRACE: "1"
  RUST_LOG: "info"